language: cpp
compiler:
  - gcc
  - clang

install:
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - ./make_unix.sh
  - cd ..

script:
  - rm -rf local/apa
  - bam/bam compiler=$CC config=debug -r sc test
  - rm -rf local/apa
  - bam/bam compiler=$CC config=release -r sc test
