language: cpp
os:
  - linux
  - osx

sudo: false

env:
  matrix:
   - DIRUTIL_CONFIG=debug
   - DIRUTIL_CONFIG=release

compiler:
  - gcc
  - clang

install:
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - ./make_unix.sh
  - cd ..

script:
  - rm -rf local/apa
  - bam/bam compiler=$CC config=$DIRUTIL_CONFIG -r sc test
